dbt-duckdb-pipeline:
  target: local
  outputs:
    aws:
      type: duckdb
      path: demo.duckdb
      extensions:
        - httpfs
        - parquet
        - json
      settings:
        s3_region: "{{ env_var('S3_REGION') }}"
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
    local:
      type: duckdb
      path: demo.duckdb
    memory:
      type: duckdb
      path: ":memory:"